icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#002b36"
idle_fg = "#93a1a1"
info_bg = "#2aa198"
info_fg = "#002b36"
good_bg = "#859900"
good_fg = "#002b36"
warning_bg = "#b58900"
warning_fg = "#002b36"
critical_bg = "#dc322f"
critical_fg = "#002b36"
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:15) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "custom"
command = "/home/axl/.local/bin/custom/vpn status"
interval = 1
[[block.click]]
button = "left"
cmd = "/home/axl/.local/bin/custom/vpn toggle"

[[block]]
block = "cpu"

[[block]]
block = "temperature"
interval = 10
format = " $icon $average|"
chip = "k10temp-*"
inputs = ["Tctl"]

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "music"

[[block]]
block = "temperature"
interval = 10
format = "GPU: $icon $average|"
chip = "amdgpu-*"
inputs = ["edge"]

#[[block]]
#block = "custom"
#command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
#interval = 600

[[block]]
block = "keyboard_layout"
driver = "sway"
#sway_kb_identifier = "1133:49948:Logitech_USB_Keyboard"
[block.mappings]
"English (US)" = "🇺🇸"
"Russian (N/A)" = "🇷🇺"


[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "




